/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMultiYieldInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "runConv0NoSwap"
      | "runConv0Swap"
      | "runConv1NoSwap"
      | "runConv1Swap"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "runConv0NoSwap",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "runConv0Swap",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "runConv1NoSwap",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "runConv1Swap",
    values: [BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "runConv0NoSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "runConv0Swap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "runConv1NoSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "runConv1Swap",
    data: BytesLike
  ): Result;
}

export interface IMultiYield extends BaseContract {
  connect(runner?: ContractRunner | null): IMultiYield;
  waitForDeployment(): Promise<this>;

  interface: IMultiYieldInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  runConv0NoSwap: TypedContractMethod<
    [tokenIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  runConv0Swap: TypedContractMethod<
    [tokenIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  runConv1NoSwap: TypedContractMethod<
    [tokenIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  runConv1Swap: TypedContractMethod<
    [tokenIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "runConv0NoSwap"
  ): TypedContractMethod<[tokenIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "runConv0Swap"
  ): TypedContractMethod<[tokenIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "runConv1NoSwap"
  ): TypedContractMethod<[tokenIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "runConv1Swap"
  ): TypedContractMethod<[tokenIds: BigNumberish[]], [void], "nonpayable">;

  filters: {};
}
