/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AutoExit } from "./AutoExit";
export type { AutoRange } from "./AutoRange";
export type { Automator } from "./Automator";
